import os
from pathlib import Path

HOST = os.environ.get("PYDROP_BIND_HOST", "127.0.0.1")
PORT = int(os.environ.get("PYDROP_PORT", "5001"))
BACKLOG = 5
BUFFER_SIZE = 4096
HEADER_LENGTH_BYTES = 4
MAX_HEADER_BYTES = 65536
STORAGE_DIR = Path(__file__).resolve().parent / "storage"
METADATA_FILE = Path(__file__).resolve().parent / "metadata" / "metadata.json"

ERROR_BAD_REQUEST = "BAD_REQUEST"
ERROR_UNKNOWN_ACTION = "UNKNOWN_ACTION"
ERROR_FILE_NOT_FOUND = "FILE_NOT_FOUND"
ERROR_INVALID_FILENAME = "INVALID_FILENAME"
ERROR_HASH_MISMATCH = "HASH_MISMATCH"
ERROR_PAYLOAD_SIZE_MISMATCH = "PAYLOAD_SIZE_MISMATCH"
ERROR_STALE_VERSION = "STALE_VERSION"
